version: "3.9"

services:

  app:
    build: .
    container_name: addlaw_app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/var/www
    networks:
      - addlaw_net_supp
    working_dir: /var/www

  web:
    image: nginx:alpine
    container_name: addlaw_web_supp
    restart: always
    ports:
      - "8081:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - addlaw_net

  queue:
    build: .
    container_name: addlaw_queue_supp
    command: php artisan queue:work --tries=3 --timeout=90
    restart: always
    depends_on:
      - app
    networks:
      - addlaw_net
    working_dir: /var/www

  scheduler:
    build: .
    container_name: addlaw_scheduler_supp
    command: sh -c "while true; do php artisan schedule:run; sleep 60; done"
    restart: always
    depends_on:
      - app
    networks:
      - addlaw_net
    working_dir: /var/www

networks:
  addlaw_net: